const $=s=>document.querySelector(s);const $$=s=>document.querySelectorAll(s);
const icons={rock:'🪨',paper:'📄',scissors:'✂️'};const names={rock:'Rock',paper:'Paper',scissors:'Scissors'};const beats={rock:'scissors',paper:'rock',scissors:'paper'};
let data=JSON.parse(localStorage.getItem('rpsArena')||'null')||{total:0,wins:0,losses:0,draws:0,best:0,perfect:0,streak:0,ach:[],history:[]};let match={p:0,a:0,round:0,streak:0,started:Date.now()};let sound=true;
const save=()=>localStorage.setItem('rpsArena',JSON.stringify(data));
function tone(freq,duration=.08){if(!sound)return;try{const c=new AudioContext(),o=c.createOscillator(),g=c.createGain();o.frequency.value=freq;o.type='sine';g.gain.value=.035;o.connect(g);g.connect(c.destination);o.start();g.gain.exponentialRampToValueAtTime(.001,c.currentTime+duration);o.stop(c.currentTime+duration)}catch(e){}}
function aiMove(player){let diff=$('#difficulty').value,mode=$('#mode').value;const choices=Object.keys(icons);if(mode==='adaptive'&&Math.random()<.68)return beats[beats[player]];if(diff==='easy')return choices[Math.floor(Math.random()*3)];if(diff==='normal')return Math.random()<.35?beats[player]:choices[Math.floor(Math.random()*3)];if(diff==='hard')return Math.random()<.72?beats[player]:choices[Math.floor(Math.random()*3)];return Math.random()<.86?beats[player]:choices[Math.floor(Math.random()*3)]}
function result(p,a){if(p===a)return'draw';return beats[p]===a?'win':'loss'}
function updateUI(){ $('#playerScore').textContent=match.p;$('#aiScore').textContent=match.a;$('#roundLabel').textContent=`ROUND ${match.round+1}`;$('#playerStreak').textContent=`${match.streak} win streak`;$('#aiStreak').textContent=`${Math.max(0,match.a-match.p)} pressure`;$('#totalRounds').textContent=data.total;$('#winRate').textContent=data.total?Math.round(data.wins/data.total*100)+'%':'0%';$('#bestStreak').textContent=data.best;$('#perfectWins').textContent=data.perfect;renderAchievements();renderHistory()}
function play(p){if(match.p>=Math.ceil(+$('#target').value/2)||match.a>=Math.ceil(+$('#target').value/2)){newMatch();return}const a=aiMove(p),r=result(p,a);match.round++;$('#playerChoice').textContent=icons[p];$('#aiChoice').textContent=icons[a];$('#playerName').textContent=names[p];$('#aiName').textContent=names[a];$('#battleText').textContent=r==='win'?'YOU WIN':r==='loss'?'AI WINS':'DRAW';$('#status').textContent=r==='win'?'NICE MOVE':r==='loss'?'OUTPLAYED':'EVEN ROUND';if(r==='win'){match.p++;match.streak++;data.wins++;data.streak++;data.best=Math.max(data.best,data.streak);tone(720,.12)}else if(r==='loss'){match.a++;match.streak=0;data.losses++;data.streak=0;tone(170,.16)}else{data.draws++;tone(430,.08)}data.total++;data.history.unshift({p,a,r});data.history=data.history.slice(0,12);if(match.p>0&&match.a===0&&match.p>=Math.ceil(+$('#target').value/2))data.perfect++;unlock();save();updateUI();if(match.p>=Math.ceil(+$('#target').value/2)||match.a>=Math.ceil(+$('#target').value/2)){setTimeout(()=>finish(),250)}}
function finish(){const win=match.p>match.a;$('#battleText').textContent=win?'🏆 MATCH WON':'💀 MATCH LOST';toast(win?'Champion! You won the match.':'Rematch? The AI got this one.');tone(win?880:120,.25)}
function newMatch(){match={p:0,a:0,round:0,streak:0,started:Date.now()};$('#playerChoice').textContent='?';$('#aiChoice').textContent='?';$('#playerName').textContent='Choose your weapon';$('#aiName').textContent='Waiting for you...';$('#battleText').textContent='READY?';$('#status').textContent='MAKE YOUR MOVE';updateUI()}
const achievementList=[['first','🎯','First Blood',()=>data.total>=1],['five','🔥','Hot Streak',()=>data.best>=5],['ten','⚡','Unstoppable',()=>data.best>=10],['perfect','👑','Flawless',()=>data.perfect>=1],['hundred','💯','Century Club',()=>data.total>=100],['win50','🏆','Elite',()=>data.wins>=50]];
function unlock(){achievementList.forEach(([id,,name,fn])=>{if(fn()&&!data.ach.includes(id)){data.ach.push(id);toast('Achievement unlocked: '+name);tone(1000,.15)}})}function renderAchievements(){$('#achievements').innerHTML=achievementList.map(([id,e,n])=>`<div class="badge ${data.ach.includes(id)?'unlocked':''}"><span>${e}</span>${n}</div>`).join('')};function renderHistory(){$('#history').innerHTML=data.history.length?data.history.map((x,i)=>`<div class="history-row"><b>#${data.history.length-i}</b><span>${icons[x.p]} ${names[x.p]}</span><span>vs ${icons[x.a]} ${names[x.a]}</span><b class="${x.r}">${x.r.toUpperCase()}</b></div>`).join(''):'<p class="empty">Your battle history will appear here.</p>'}
function toast(t){const e=$('#toast');e.textContent=t;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),2200)}
$$('.move').forEach(b=>b.addEventListener('click',()=>play(b.dataset.move)));document.addEventListener('keydown',e=>{if(e.key.toLowerCase()==='r')play('rock');if(e.key.toLowerCase()==='p')play('paper');if(e.key.toLowerCase()==='s')play('scissors')});$('#newMatch').onclick=newMatch;$('#soundBtn').onclick=()=>{sound=!sound;$('#soundBtn').textContent=sound?'🔊':'🔇'};$('#themeBtn').onclick=()=>{document.body.classList.toggle('light');$('#themeBtn').textContent=document.body.classList.contains('light')?'🌙':'☀️';localStorage.setItem('rpsTheme',document.body.classList.contains('light')?'light':'dark')};$('#resetStats').onclick=()=>{if(confirm('Reset all stats and achievements?')){data={total:0,wins:0,losses:0,draws:0,best:0,perfect:0,streak:0,ach:[],history:[]};save();newMatch()}};$('#clearHistory').onclick=()=>{data.history=[];save();updateUI()};$('#year').textContent=new Date().getFullYear();if(localStorage.getItem('rpsTheme')==='light'){$('#themeBtn').click()}updateUI();
